### PR TITLE
Fix #256

### LINKED ISSUE #256: Method changePage doesn't working to same page
**Scenario**
Imagine the 'search screen' where user can fill input with keyword to search items. Now imagine witch search screen need be something like `#!search/keyword-to-search` this will allow search any item from any screen...

Using this way, when user is on 'search screen' all time when him typed some keywords only hash will be changed like `#!search/keyword-2` and `#!search/keyword-3`... Very simple, right?

**Problem**
When using component `phonon.navigator().changePage( 'search', 'keyword-2' )` nothing happening, because user alright in 'search' screen, but is necessary change the param.

**Solution**
Until next version of Phonon you can use `window.location.replace( "#!search/your-keyword" )` in cases like this.

### PR DESCRIPTION
**Pull request by kserin**
Fix #256 : don't change page only when the entire new hash match the current hash

I don't know why only the first part of the path was used o check if we need to change page or not : 
`var parsed = window.location.hash.split('/');
if(parsed[0].indexOf(pageObject.name)) ...`

I removed that and use the all path to check if we need redirection. Maybe someone should check if I don't break a wanted behavior.

### CODE REVIEW

**Comment by John-Henrique** [comment]
@kserin please, can you fix conflict  ;-)

**Comment by kserin** [comment]
@John-Henrique Done ;)

**Comment by Qathom** [comment]
Hi @kserin,

Thank you for your contribution!

**Comment by John-Henrique** [comment]
@kserin 
@Qathom 
Thanks guys

**Pull request merged**
