### PR TITLE
Allow display in center of screen

### PR DESCRIPTION
**Pull request by John-Henrique**
Center of screen by using

```
		<div class="circle-progress center">
			<div class="spinner"></div>
		</div>
```

### CODE REVIEW

**Comment by Qathom** [comment]
Hi @John-Henrique,

Preloaders should be used in `.content` and the circle preloader is always centered normally.
It is not the case for you?

**Comment by John-Henrique** [comment]
Yes, is working as you said. My changes allow display in center by X and Y of screen... see
phonon-preloader-after-before

**Comment by John-Henrique** [comment]
@Qathom this changes isn't interesting for you?

**Comment by Qathom** [comment]
@John-Henrique : the idea is good! However, you didn't use Stylus.
I merge your pull request, but I have to edit some lines.
I warn you of the changes.

**Comment by Qathom** [comment]
@John-Henrique : the following edition has been made:

```stylus
  &.center
      top 50%
      left 50%
      margin-top -(preloader-spinner-size/2)
      position absolute
```

**Comment by John-Henrique** [comment]
@Qathom I will learn how to use Stylus, this week 👍 

Tested
Working on 1.4.2

Thanks

**Comment by Qathom** [comment]
@John-Henrique : **Stylus** is the preprocessor used in Phonon right now, but very soon **Sass** will be used instead (it is better). You should try them quickly, I think that you will see that Sass is better ;).

**Pull request merged**
